package:
    name: "libhydromath"
    version: "0.2.0"
source:
    #git_url: https://github.com/amacd31/hydromath.git
    #git_rev: master
    path: ../
requirements:
    build:
        - gcc         # [unix]
        - cmake       # [unix]
    run:
        - libgcc      # [unix]
