package:
    name: "libhydromath"
    version: {{ environ['GIT_DESCRIBE_TAG'][1:] }}
build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
source:
  git_url: ../
requirements:
    build:
        - gcc         # [unix]
        - cmake       # [unix]
    run:
        - libgcc      # [unix]
